version: '2'
services:
  spark-master:
    build: .
    ports:
      - "2222:22"
      - "8081:8080"
      - "7077:7077"
      - "6066:6066"
    environment:
      SPARK_INSTANCE_TYPE: master
      SPARK_MASTER_HOST: spark-master
    volumes:
      - ${CORE_BRIDGES_PATH}:${CORE_BRIDGES_PATH}
    # networks:
    #   - vizix-network
    external_links:
      - hazelcast1
      - mysql
      - mosquitto
      - mongo

  spark-slave:
    build: .
    environment:
      SPARK_INSTANCE_TYPE: slave
      SPARK_MASTER_HOST: spark-master
    volumes:
      - ${CORE_BRIDGES_PATH}:${CORE_BRIDGES_PATH}
    # networks:
    #   - vizix-network
    external_links:
      - hazelcast1
      - mysql
      - mosquitto
      - mongo
networks:
  default:
    external:
      name: vizix-network
