version: '2'
services:
  spark-master:
    build: . 
    ports:
      - "2222:22"
      - "8081:8080"
      - "7077:7077"
      - "6066:6066"
    environment:
      SPARK_INSTANCE_TYPE: master
      SPARK_MASTER_HOST: spark-master
  spark-slave:
    build: .
    environment:
      SPARK_INSTANCE_TYPE: slave
      SPARK_MASTER_HOST: spark-master
    links:
      - spark-master
